// Bakes the 3D emoji pictures the studio formats use into src/studio/art-data.js,
// so the page and the renderer draw Fluent Emoji 3D (Microsoft, MIT) instead of
// the system's flat emoji font. Rerun after adding an emoji to a format.
import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';

const root = new URL('..', import.meta.url);
const assets = new URL('node_modules/@lobehub/fluent-emoji-3d/assets/', root);
const sources = ['pause.js', 'survive.js', 'odd.js'];
const re = /\p{Extended_Pictographic}(?:️|‍\p{Extended_Pictographic}|\p{Emoji_Modifier})*/gu;

const key = (e) => [...e].map((c) => c.codePointAt(0).toString(16)).filter((c) => c !== 'fe0f').join('-');
const found = new Map();
for (const f of sources) {
  const text = await readFile(new URL(`src/studio/${f}`, root), 'utf8');
  for (const [e] of text.matchAll(re)) found.set(key(e), e);
}

const out = {};
const missing = [];
for (const [k, e] of found) {
  // asset names keep fe0f on some emoji and drop it on others
  const cps = [...e].map((c) => c.codePointAt(0).toString(16));
  const name = [cps.join('-'), k].find((n) => existsSync(new URL(`${n}.webp`, assets)));
  if (!name) { missing.push(e); continue; }
  out[k] = 'data:image/webp;base64,' + (await readFile(new URL(`${name}.webp`, assets))).toString('base64');
}
await writeFile(new URL('src/studio/art-data.js', root),
  `// Generated by scripts/build-art.mjs from @lobehub/fluent-emoji-3d (MIT). Do not edit.\nexport default ${JSON.stringify(out)};\n`);
console.log(`art-data.js: ${Object.keys(out).length} pictures${missing.length ? ', no picture for ' + missing.join(' ') : ''}`);
